### ISSUE TITLE
Resistor for REXT[A,B,C]

### ISSUE THREAD

**Issue by jnrivra** [xoseperez/my92xx#2]
Hey! 

by any chance do you have a better datasheet of the My9231? cant figure out whats the resistor value for the mA of the OUT[A,B,C], any ideas?

thanks!

**Comment by xoseperez** [comment]
The datasheet in the repo is the latest available from the MY-SEMI web page:

http://www.my-semi.com.tw/content/products/product_mean.aspx?id=5

**Comment by jnrivra** [comment]
i checked it but it has only one page, found the chinese version but its really difficult to translate, do you have an english one? thanks :)

**Comment by xoseperez** [comment]
No, I don't have the English version.
