### ISSUE TITLE
LEDs stay dark with a bit length > 8 on ESP-01

### ISSUE THREAD

**Issue by kduve** [xoseperez/my92xx#4]
Hi,
thanks for this lib! You should change
digitalWrite(_pin_di, (data & mask));
to
digitalWrite(_pin_di, ((data & mask)?HIGH:LOW));
when using a bit length > 8 on ESP-01 (ESP8266).

At least that fixed the problem for me.
Best
K

**Comment by xoseperez** [comment]
Thank you, fixed with new release.
