### ISSUE TITLE
test

### ISSUE THREAD

**Issue by ghost** [xoseperez/my92xx#5]

**Comment by xoseperez** [comment]
It's supported but not tested. The last argument in the constructor is the configuration command. By default, this is defined as:

https://github.com/xoseperez/my92xx/blob/cda124a305e6440ba1ef7fd6bdfc2b130b9af070/src/my92xx.h#L82-L89

Changing the bit_width to MY92XX_CMD_BIT_WIDTH_16 should do the trick.

**Comment by bob808** [comment]
I tried but it didn't work. I tried to find a datasheet but didn't find any. I found the datasheet for my9221 and found this info: https://i.imgur.com/rfLrDbT.png
I presume this is the write command function:
`void my92xx::_write(unsigned int data, unsigned char bit_length) {

    unsigned int mask = (0x01 << (bit_length - 1));

    for (unsigned int i = 0; i < bit_length / 2; i++) {
        digitalWrite(_pin_dcki, LOW);
        digitalWrite(_pin_di, (data & mask) ? HIGH : LOW);
        digitalWrite(_pin_dcki, HIGH);
        data = data << 1;
        digitalWrite(_pin_di, (data & mask) ? HIGH : LOW);
        digitalWrite(_pin_dcki, LOW);
        digitalWrite(_pin_di, LOW);
        data = data << 1;
    }

}`
